### ISSUE TITLE
Case conversion error

### ISSUE THREAD

**Issue by telppa** [G33kDude/cJson.ahk#2]
```
a=
(
{
	"char": {
		"*LPSTR": 0,
		"*PCHAR": 0,
		"*PSTR": 0,
		"CCHAR": 0,
		"CHAR": 0
	}
}
)

aa:=json.load(a)

for k, v in aa
	MsgBox, % k		; should be char, but it shows CHAR

ExitApp

#Include <json>
```

**Comment by G33kDude** [comment]
This appears to be a bug with AHK, please file a report over in the bugs forum:

```autoit
js =
(
<script>
function test(Object) {
	var outer = Object();
	var inner = Object();
	inner["TEST"] = 1;
	outer["test"] = inner;
	return outer;
}
</script>
)

doc := ComObjCreate("htmlfile")
doc.Write(js)
doc.Close()

outer := doc.parentWindow.test(Func("Object"))

outer._NewEnum().Next(k1, inner)
inner._NewEnum().Next(k2, v2)
MsgBox, {"%k1%": {"%k2%": "%v2%"}} ; shows {"TEST": {"TEST": "1"}}
```

**Comment by telppa** [comment]
> This appears to be a bug with AHK, please file a report over in the bugs forum:
> 
> ```autoit
> js =
> (
> <script>
> function test(Object) {
> 	var outer = Object();
> 	var inner = Object();
> 	inner["TEST"] = 1;
> 	outer["test"] = inner;
> 	return outer;
> }
> </script>
> )
> 
> doc := ComObjCreate("htmlfile")
> doc.Write(js)
> doc.Close()
> 
> outer := doc.parentWindow.test(Func("Object"))
> 
> outer._NewEnum().Next(k1, inner)
> inner._NewEnum().Next(k2, v2)
> MsgBox, {"%k1%": {"%k2%": "%v2%"}} ; shows {"TEST": {"TEST": "1"}}
> ```

I didn't understand the code, maybe you can report bugs in the forum?

**Comment by G33kDude** [comment]
Being tracked at https://www.autohotkey.com/boards/viewtopic.php?f=14&t=100622

**Comment by G33kDude** [comment]
This has been fixed in the AHK interpreter.
