### ISSUE TITLE
`JSON.Dump` converts float numbers to string 

### ISSUE THREAD

**Issue by htadashi** [G33kDude/cJson.ahk#6]
Thank you for your fantastic work. Your project has been an immense help to me during my [recent AHK project](https://github.com/htadashi/GPT3-AHK), and I'm grateful for the time and effort you put into it. 

However, I wanted to bring a small issue to your attention. I noticed that the method `JSON.Dump` automatically converts float numbers to a string. While this works in most cases, some servers expect the parameter to be a float instead of a string. This can cause issues for users who are trying to send data to these servers.

**Comment by G33kDude** [comment]
Please refer to the type conversions table in the Readme. It explains how float conversions work, and how to make them do what you've asked here. If you have any further questions, feel free to re-open the issue.

**Comment by htadashi** [comment]
Thanks @G33kDude! This solves my issue.
