### ISSUE TITLE
Unnecessary escaping of strings

### ISSUE THREAD

**Issue by l-noesis** [G33kDude/cJson.ahk#8]
According to RFC4627[ https://www.rfc-editor.org/rfc/rfc4627#section-2.5 ], strings do not need escaping except for some prohibited characters.
However, cjson.ahk seems to escape all characters except US-ASCII. This replaces my native language with numbers and eliminates the readability and versatility of JSON.
If you feel up to it, I would appreciate it if you could create a switch to work around this.

**Comment by G33kDude** [comment]
This has been supported since January 2022: 9b01c6e384e4855637cf17893b3c4feefb94afe7
